name: Update Page

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install Dependencies
      run: go install github.com/snowmerak/snowiki@v0.1.0

    - name: Build Public
      run: snowiki

    - name: Git Config
      run: | 
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Git Commit & Push
      run: |
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -m "Update Wiki Pages `date`"
          git push origin main
        else
          echo "Nothing to commit, working directory clean."
        fi 
